name: pcpp-workflow
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - snakemake
# optional: complete and uncomment the 'variables' block
# see also: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#setting-environment-variables
variables:
  SNAKEMAKE_CONDA_PREFIX: /scratch/fzanetta/pcpp-workflow/conda
  # SNAKEMAKE_DATA_DIR: /directory/where/to/save/mlpp/datasets